#!/bin/sh
docker run --rm -it \
	-u $UID:$UID \
	-e XDG_CACHE_HOME=/tmp/.cache \
	-e GOPROXY=https://goproxy.cn \
	-e CGO_ENABLED=0 \
    	-e GOOS=linux \
    	-e GOARCH=amd64 \
	-v $PWD:/srv/app \
	-v ~/Services/go:/go \
	-w /srv/app \
	golang:alpine go build $@
